"""initial migration

Revision ID: a886509bb768
Revises: c5d10945ce48
Create Date: 2022-06-16 15:25:05.134369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a886509bb768'
down_revision = 'c5d10945ce48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('post', sa.Column('published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'published')
    op.drop_column('post', 'is_deleted')
    # ### end Alembic commands ###
