"""Change default value of publiced_date

Revision ID: da2f0f3f799c
Revises: a886509bb768
Create Date: 2022-06-16 16:24:56.803580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2f0f3f799c'
down_revision = 'a886509bb768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('publisted_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('post', 'published_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('published_date', sa.DATETIME(), nullable=True))
    op.drop_column('post', 'publisted_date')
    # ### end Alembic commands ###
